import { Audit, AuditStatus, Issue, PageData, Scores } from '../types';

const generateRandomScore = (min = 40, max = 100) => Math.floor(Math.random() * (max - min + 1)) + min;

const MOCK_ISSUES_POOL: Omit<Issue, 'id' | 'pageUrl'>[] = [
  { category: 'seo', code: 'MISSING_META_DESC', severity: 'major', message: 'Page is missing meta description tag.' },
  { category: 'seo', code: 'H1_MISSING', severity: 'critical', message: 'No H1 heading found on the page.' },
  { category: 'performance', code: 'SLOW_LCP', severity: 'major', message: 'Largest Contentful Paint exceeds 2.5s.' },
  { category: 'performance', code: 'HIGH_TBT', severity: 'major', message: 'Total Blocking Time is too high (>300ms).' },
  { category: 'accessibility', code: 'COLOR_CONTRAST', severity: 'critical', message: 'Text does not meet WCAG AA contrast ratio.' },
  { category: 'accessibility', code: 'IMG_ALT_MISSING', severity: 'minor', message: 'Images found without alt text.' },
  { category: 'uxDesign', code: 'NO_CTA_ABOVE_FOLD', severity: 'major', message: 'No primary Call-to-Action visible above the fold.' },
  { category: 'uxDesign', code: 'FONT_INCONSISTENCY', severity: 'minor', message: 'More than 3 font families detected.' },
  { category: 'content', code: 'ORPHAN_PAGE', severity: 'minor', message: 'Page has no internal links pointing to it.' },
];

const generateReport = (url: string, scores: Scores): string => {
  return `
# Audit Report for ${url}

## Executive Summary
This website has been audited by **Audit Forge**. The overall health score is **${scores.overall}/100**. 
While the foundation is solid, there are critical issues in **UX/Design** and **Performance** that may be affecting conversion rates.

**Key Strengths:**
* Good Content structure.
* Accessibility compliance is generally high.

**Top Priority Fixes:**
1. Fix layout shifts on mobile devices.
2. Ensure the primary "Book Now" or "Contact" button is visible immediately on load.
3. Add meta descriptions to key landing pages.

---

## Detailed Analysis

### 🎨 Design & UX (${scores.uxDesign}/100)
The visual hierarchy is generally clear, but we detected **4 font families** loaded, which slows down rendering and creates visual clutter. 
* **Critical:** On mobile, the "Contact" button is pushed below the fold.
* **Observation:** Color contrast on secondary buttons is too low (Ratio 3.5:1).

### 🚀 Performance (${scores.performance}/100)
Core Web Vitals assessment indicates the site passes LCP but fails CLS (Cumulative Layout Shift).
* **Speed Index:** 3.4s (Needs Improvement)
* **Total Blocking Time:** 120ms (Good)

### 🔍 SEO (${scores.seo}/100)
Technical SEO is decent. However, 30% of scanned pages lack a unique Meta Description. 
This hurts Click-Through-Rate (CTR) from search engines.

---

## Action Plan
We recommend a 2-sprint fix cycle:
- **Week 1:** Fix Critical UX issues (CTA placement) and Server-Side Rendering configuration for Performance.
- **Week 2:** Address Content gaps (Meta descriptions) and minor Accessibility labels.

*Generated by Audit Forge AI Consultant*
  `;
};

export const generateMockAuditResult = (audit: Audit): Audit => {
  const pageCount = 5;
  const pages: PageData[] = [];
  let totalIssues = { critical: 0, major: 0, minor: 0, byCategory: { seo: 0, performance: 0, accessibility: 0, content: 0, uxDesign: 0 } };

  for (let i = 0; i < pageCount; i++) {
    const isHome = i === 0;
    const pageUrl = isHome ? audit.url : `${audit.url}/page-${i}`;
    
    // Generate page scores
    const scores: Scores = {
      overall: 0,
      seo: generateRandomScore(50, 95),
      performance: generateRandomScore(30, 90),
      accessibility: generateRandomScore(70, 100),
      content: generateRandomScore(60, 90),
      uxDesign: generateRandomScore(40, 85),
    };
    scores.overall = Math.round((scores.seo + scores.performance + scores.accessibility + scores.content + scores.uxDesign) / 5);

    // Generate issues for this page
    const pageIssues: Issue[] = [];
    const issueCount = Math.floor(Math.random() * 4);
    for (let j = 0; j < issueCount; j++) {
      const template = MOCK_ISSUES_POOL[Math.floor(Math.random() * MOCK_ISSUES_POOL.length)];
      pageIssues.push({
        ...template,
        id: `issue-${i}-${j}`,
        pageUrl: pageUrl
      });

      // Update summary
      totalIssues[template.severity]++;
      totalIssues.byCategory[template.category]++;
    }

    pages.push({
      id: `page-${i}`,
      url: pageUrl,
      statusCode: 200,
      scores,
      issues: pageIssues,
      seoData: {
        title: isHome ? "Home Page - Best Service" : `Page ${i} Title`,
        description: Math.random() > 0.5 ? "A good description." : "",
        h1Count: 1,
        wordCount: 500 + Math.floor(Math.random() * 1000)
      },
      designUxData: {
        fontFamilies: 3,
        hasPrimaryCtaAboveFold: isHome ? false : true, // Simulate the error on homepage
        mobileUsabilityScore: 0.85
      }
    });
  }

  // Calculate audit-level scores (averages)
  const auditScores: Scores = {
    seo: Math.round(pages.reduce((acc, p) => acc + p.scores.seo, 0) / pageCount),
    performance: Math.round(pages.reduce((acc, p) => acc + p.scores.performance, 0) / pageCount),
    accessibility: Math.round(pages.reduce((acc, p) => acc + p.scores.accessibility, 0) / pageCount),
    content: Math.round(pages.reduce((acc, p) => acc + p.scores.content, 0) / pageCount),
    uxDesign: Math.round(pages.reduce((acc, p) => acc + p.scores.uxDesign, 0) / pageCount),
    overall: 0
  };
  auditScores.overall = Math.round(
    (auditScores.seo + auditScores.performance + auditScores.accessibility + auditScores.content + auditScores.uxDesign) / 5
  );

  return {
    ...audit,
    status: AuditStatus.COMPLETED,
    completedAt: new Date().toISOString(),
    scores: auditScores,
    pages,
    issuesSummary: totalIssues,
    reportMarkdown: generateReport(audit.url, auditScores)
  };
};